{
  "stats": {
    "submitted": 82,
    "finished": 69,
    "running": 13
  },
  "data": [
    [
      1,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368870.5811713,
      1706368881.6425319,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      2,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368870.592607,
      1706368880.5958266,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      3,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368870.5944633,
      1706368881.6525178,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      4,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368870.6044881,
      1706368881.4822795,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      5,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368870.616899,
      1706368881.2630503,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      6,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368870.6330125,
      1706368881.9363592,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      7,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368870.6559854,
      1706368881.6006205,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      8,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368870.7017646,
      1706368881.1363258,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      9,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368870.7386074,
      1706368881.5657096,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      10,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368870.801772,
      1706368881.8429794,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      11,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368870.8624606,
      1706368882.236862,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      12,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368870.907518,
      1706368882.110056,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      13,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368871.0236938,
      1706368881.9496229,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      14,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368871.3138683,
      1706368882.1962764,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      15,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368871.77991,
      1706368882.3599746,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      16,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368872.1179779,
      1706368882.3268142,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      17,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368881.0073774,
      1706368885.5734699,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      2,
      null,
      1044794247,
      null,
      Infinity,
      0.0,
      2,
      1706368881.6267354,
      1706368885.995745,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      18,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368881.9691296,
      1706368886.594161,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      19,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368882.2253237,
      1706368886.7416167,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      20,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368882.2910352,
      1706368887.0632439,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      21,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368885.7218006,
      1706368894.6324296,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      22,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368885.8072615,
      1706368895.4234133,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      23,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368885.849194,
      1706368895.890172,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      24,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368885.8804057,
      1706368895.5380318,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      25,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368885.9167264,
      1706368896.4557369,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      26,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368885.966689,
      1706368895.5076315,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      27,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368886.0088818,
      1706368896.0128078,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      28,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368886.0821512,
      1706368896.2526035,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      2,
      null,
      119466228,
      null,
      Infinity,
      0.0,
      2,
      1706368886.1873136,
      1706368896.3421602,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      29,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368887.1528819,
      1706368898.0656226,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      18,
      null,
      1044794247,
      null,
      Infinity,
      0.0,
      2,
      1706368887.3847077,
      1706368897.52948,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      19,
      null,
      1044794247,
      null,
      Infinity,
      0.0,
      2,
      1706368887.455105,
      1706368898.9122794,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      20,
      null,
      1044794247,
      null,
      Infinity,
      0.0,
      2,
      1706368887.5473108,
      1706368898.02755,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      30,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368887.7275012,
      1706368898.1619718,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      31,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368887.820242,
      1706368898.6462488,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      32,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368887.9041896,
      1706368898.4937177,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      33,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368894.8864372,
      1706368905.679242,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      21,
      null,
      1044794247,
      null,
      Infinity,
      0.0,
      2,
      1706368895.957027,
      1706368907.1509302,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      22,
      null,
      1044794247,
      null,
      Infinity,
      0.0,
      2,
      1706368896.1148415,
      1706368906.5760148,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      23,
      null,
      1044794247,
      null,
      Infinity,
      0.0,
      2,
      1706368896.3989854,
      1706368907.3210964,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      24,
      null,
      1044794247,
      null,
      Infinity,
      0.0,
      2,
      1706368896.622172,
      1706368906.8998146,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      25,
      null,
      1044794247,
      null,
      Infinity,
      0.0,
      2,
      1706368896.8421319,
      1706368907.796879,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      26,
      null,
      1044794247,
      null,
      Infinity,
      0.0,
      2,
      1706368896.8858001,
      1706368908.2017636,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      27,
      null,
      1044794247,
      null,
      Infinity,
      0.0,
      2,
      1706368896.96202,
      1706368908.0210068,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      28,
      null,
      1044794247,
      null,
      Infinity,
      0.0,
      2,
      1706368897.147529,
      1706368908.3654222,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      34,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368897.7465572,
      1706368908.3151393,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      18,
      null,
      119466228,
      null,
      Infinity,
      0.0,
      2,
      1706368898.3636248,
      1706368909.1912396,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      29,
      null,
      1044794247,
      null,
      Infinity,
      0.0,
      2,
      1706368898.5546567,
      1706368909.5793226,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      20,
      null,
      119466228,
      null,
      Infinity,
      0.0,
      2,
      1706368898.7346597,
      1706368910.1977444,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      30,
      null,
      1044794247,
      null,
      Infinity,
      0.0,
      2,
      1706368898.8885775,
      1706368910.158254,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      31,
      null,
      1044794247,
      null,
      Infinity,
      0.0,
      2,
      1706368898.9266453,
      1706368909.4857507,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      32,
      null,
      1044794247,
      null,
      Infinity,
      0.0,
      2,
      1706368899.1559284,
      1706368910.3513014,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      19,
      null,
      119466228,
      null,
      Infinity,
      0.0,
      2,
      1706368905.92986,
      1706368916.9185889,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      33,
      null,
      1044794247,
      null,
      Infinity,
      0.0,
      2,
      1706368906.8738322,
      1706368917.903508,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      22,
      null,
      119466228,
      null,
      Infinity,
      0.0,
      2,
      1706368907.0242953,
      1706368917.8275928,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      24,
      null,
      119466228,
      null,
      Infinity,
      0.0,
      2,
      1706368907.3728008,
      1706368918.6497507,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      21,
      null,
      119466228,
      null,
      Infinity,
      0.0,
      2,
      1706368907.535707,
      1706368918.170936,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      23,
      null,
      119466228,
      null,
      Infinity,
      0.0,
      2,
      1706368907.9131303,
      1706368919.0731285,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      25,
      null,
      119466228,
      null,
      Infinity,
      0.0,
      2,
      1706368908.1464822,
      1706368919.6543562,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      27,
      null,
      119466228,
      null,
      Infinity,
      0.0,
      2,
      1706368908.4422271,
      1706368919.7334194,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      26,
      null,
      119466228,
      null,
      Infinity,
      0.0,
      2,
      1706368908.7639318,
      1706368920.1810167,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      28,
      null,
      119466228,
      null,
      Infinity,
      0.0,
      2,
      1706368908.870579,
      1706368920.4333973,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      34,
      null,
      1044794247,
      null,
      Infinity,
      0.0,
      2,
      1706368909.376119,
      1706368919.749394,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      35,
      null,
      1038882193,
      null,
      Infinity,
      0.0,
      2,
      1706368909.563817,
      1706368920.0014637,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      31,
      null,
      119466228,
      null,
      Infinity,
      0.0,
      2,
      1706368909.7560146,
      1706368920.501237,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      29,
      null,
      119466228,
      null,
      Infinity,
      0.0,
      2,
      1706368910.310352,
      1706368920.4926805,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      30,
      null,
      119466228,
      null,
      Infinity,
      0.0,
      2,
      1706368910.5293517,
      1706368920.7031133,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      32,
      null,
      119466228,
      null,
      Infinity,
      0.0,
      2,
      1706368910.6886477,
      1706368920.788455,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/leon/PycharmProjects/SeminarIntelligentSystemsRegression/Models/ensemble_trainer.py\", line 54, in ensemble_error\n    error = mean_squared_error(validation_targets, final_predictions, squared=False)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 474, in mean_squared_error\n    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/metrics/_regression.py\", line 99, in _check_reg_targets\n    check_consistent_length(y_true, y_pred)\n  File \"/home/leon/.conda/envs/SeminarIntelligentSystemsRegression/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 409, in check_consistent_length\n    raise ValueError(\nValueError: Found input variables with inconsistent numbers of samples: [161130, 21824]\n",
        "error": "ValueError('Found input variables with inconsistent numbers of samples: [161130, 21824]')"
      }
    ],
    [
      36,
      null,
      1038882193,
      null,
      2147483647.0,
      0.0,
      0,
      0.0,
      0.0,
      {}
    ],
    [
      37,
      null,
      1038882193,
      null,
      2147483647.0,
      0.0,
      0,
      0.0,
      0.0,
      {}
    ],
    [
      33,
      null,
      119466228,
      null,
      2147483647.0,
      0.0,
      0,
      0.0,
      0.0,
      {}
    ],
    [
      38,
      null,
      1038882193,
      null,
      2147483647.0,
      0.0,
      0,
      0.0,
      0.0,
      {}
    ],
    [
      34,
      null,
      119466228,
      null,
      2147483647.0,
      0.0,
      0,
      0.0,
      0.0,
      {}
    ],
    [
      35,
      null,
      1044794247,
      null,
      2147483647.0,
      0.0,
      0,
      0.0,
      0.0,
      {}
    ],
    [
      39,
      null,
      1038882193,
      null,
      2147483647.0,
      0.0,
      0,
      0.0,
      0.0,
      {}
    ],
    [
      40,
      null,
      1038882193,
      null,
      2147483647.0,
      0.0,
      0,
      0.0,
      0.0,
      {}
    ],
    [
      41,
      null,
      1038882193,
      null,
      2147483647.0,
      0.0,
      0,
      0.0,
      0.0,
      {}
    ],
    [
      42,
      null,
      1038882193,
      null,
      2147483647.0,
      0.0,
      0,
      0.0,
      0.0,
      {}
    ],
    [
      43,
      null,
      1038882193,
      null,
      2147483647.0,
      0.0,
      0,
      0.0,
      0.0,
      {}
    ],
    [
      44,
      null,
      1038882193,
      null,
      2147483647.0,
      0.0,
      0,
      0.0,
      0.0,
      {}
    ],
    [
      45,
      null,
      1038882193,
      null,
      2147483647.0,
      0.0,
      0,
      0.0,
      0.0,
      {}
    ]
  ],
  "configs": {
    "1": {
      "weight1": 0.758469014428556,
      "weight2": 0.5212763994932175
    },
    "2": {
      "weight1": 0.4503632327541709,
      "weight2": 0.4441064866259694
    },
    "3": {
      "weight1": 0.10847197938710451,
      "weight2": 0.8227227563038468
    },
    "4": {
      "weight1": 0.6665777312591672,
      "weight2": 0.1498926766216755
    },
    "5": {
      "weight1": 0.5090992450714111,
      "weight2": 0.8925788113847375
    },
    "6": {
      "weight1": 0.20001716911792755,
      "weight2": 0.06351680681109428
    },
    "7": {
      "weight1": 0.3583299908787012,
      "weight2": 0.7009220197796822
    },
    "8": {
      "weight1": 0.9174120966345072,
      "weight2": 0.27998403180390596
    },
    "9": {
      "weight1": 0.947337637655437,
      "weight2": 0.7933181319385767
    },
    "10": {
      "weight1": 0.2652091635391116,
      "weight2": 0.24933320935815573
    },
    "11": {
      "weight1": 0.16960808727890253,
      "weight2": 0.6131790904328227
    },
    "12": {
      "weight1": 0.6017365911975503,
      "weight2": 0.40716402046382427
    },
    "13": {
      "weight1": 0.6991564221680164,
      "weight2": 0.6675520492717624
    },
    "14": {
      "weight1": 0.014097992330789566,
      "weight2": 0.36776878498494625
    },
    "15": {
      "weight1": 0.4182776194065809,
      "weight2": 0.9884507227689028
    },
    "16": {
      "weight1": 0.8533360194414854,
      "weight2": 0.038233994506299496
    },
    "17": {
      "weight1": 0.8172258464619517,
      "weight2": 0.9609148129820824
    },
    "18": {
      "weight1": 0.37630759458988905,
      "weight2": 0.004824389703571796
    },
    "19": {
      "weight1": 0.034582206048071384,
      "weight2": 0.6330743292346597
    },
    "20": {
      "weight1": 0.7255004877224565,
      "weight2": 0.33916475996375084
    },
    "21": {
      "weight1": 0.8249338372259237,
      "weight2": 0.3014010835890457
    },
    "22": {
      "weight1": 0.7454117605842633,
      "weight2": 0.11086624658426336
    },
    "23": {
      "weight1": 0.6940270411341372,
      "weight2": 0.19878493294017496
    },
    "24": {
      "weight1": 0.6735832420066387,
      "weight2": 0.890182158590035
    },
    "25": {
      "weight1": 0.5992475615257787,
      "weight2": 0.7065610858823513
    },
    "26": {
      "weight1": 0.405445884000057,
      "weight2": 0.9146101314893896
    },
    "27": {
      "weight1": 0.24188361125633207,
      "weight2": 0.5520589864750287
    },
    "28": {
      "weight1": 0.027815401254098093,
      "weight2": 0.18570894768001112
    },
    "29": {
      "weight1": 0.6949846232154602,
      "weight2": 0.10072524349312639
    },
    "30": {
      "weight1": 0.8139278757651962,
      "weight2": 0.18645542987738795
    },
    "31": {
      "weight1": 0.27249773700163893,
      "weight2": 0.7955689775479106
    },
    "32": {
      "weight1": 0.4414872819103176,
      "weight2": 0.5403980973871755
    },
    "33": {
      "weight1": 0.01959736596307704,
      "weight2": 0.49617388832338327
    },
    "34": {
      "weight1": 0.5475341983470494,
      "weight2": 0.5437542353520923
    },
    "35": {
      "weight1": 0.20536492687539498,
      "weight2": 0.051610189854702226
    },
    "36": {
      "weight1": 0.9190403290803709,
      "weight2": 0.8398619696704626
    },
    "37": {
      "weight1": 0.6835351125089857,
      "weight2": 0.1680634828968245
    },
    "38": {
      "weight1": 0.7764616935177638,
      "weight2": 0.6955972116924241
    },
    "39": {
      "weight1": 0.7014576979904121,
      "weight2": 0.007995202153695535
    },
    "40": {
      "weight1": 0.1945584795335773,
      "weight2": 0.8196184459764229
    },
    "41": {
      "weight1": 0.115411347555464,
      "weight2": 0.016900803089746064
    },
    "42": {
      "weight1": 0.32842330090719085,
      "weight2": 0.8132937355036819
    },
    "43": {
      "weight1": 0.5272357163929329,
      "weight2": 0.23506709546997395
    },
    "44": {
      "weight1": 0.23547733977032048,
      "weight2": 0.21973127641658496
    },
    "45": {
      "weight1": 0.9536417824576783,
      "weight2": 0.43460075961309896
    }
  },
  "config_origins": {
    "1": "Initial Design: Sobol",
    "2": "Initial Design: Sobol",
    "3": "Initial Design: Sobol",
    "4": "Initial Design: Sobol",
    "5": "Initial Design: Sobol",
    "6": "Initial Design: Sobol",
    "7": "Initial Design: Sobol",
    "8": "Initial Design: Sobol",
    "9": "Initial Design: Sobol",
    "10": "Initial Design: Sobol",
    "11": "Initial Design: Sobol",
    "12": "Initial Design: Sobol",
    "13": "Initial Design: Sobol",
    "14": "Initial Design: Sobol",
    "15": "Initial Design: Sobol",
    "16": "Initial Design: Sobol",
    "17": "Initial Design: Sobol",
    "18": "Initial Design: Sobol",
    "19": "Initial Design: Sobol",
    "20": "Initial Design: Sobol",
    "21": "Acquisition Function Maximizer: Random Search (sorted)",
    "22": "Acquisition Function Maximizer: Random Search (sorted)",
    "23": "Acquisition Function Maximizer: Random Search (sorted)",
    "24": "Acquisition Function Maximizer: Random Search (sorted)",
    "25": "Acquisition Function Maximizer: Random Search (sorted)",
    "26": "Acquisition Function Maximizer: Random Search (sorted)",
    "27": "Acquisition Function Maximizer: Random Search (sorted)",
    "28": "Acquisition Function Maximizer: Random Search (sorted)",
    "29": "Acquisition Function Maximizer: Random Search (sorted)",
    "30": "Acquisition Function Maximizer: Random Search (sorted)",
    "31": "Acquisition Function Maximizer: Random Search (sorted)",
    "32": "Acquisition Function Maximizer: Random Search (sorted)",
    "33": "Acquisition Function Maximizer: Random Search (sorted)",
    "34": "Acquisition Function Maximizer: Random Search (sorted)",
    "35": "Random Search",
    "36": "Random Search",
    "37": "Random Search",
    "38": "Acquisition Function Maximizer: Random Search (sorted)",
    "39": "Acquisition Function Maximizer: Random Search (sorted)",
    "40": "Acquisition Function Maximizer: Random Search (sorted)",
    "41": "Acquisition Function Maximizer: Random Search (sorted)",
    "42": "Acquisition Function Maximizer: Random Search (sorted)",
    "43": "Acquisition Function Maximizer: Random Search (sorted)",
    "44": "Acquisition Function Maximizer: Random Search (sorted)",
    "45": "Random Search"
  }
}